### ISSUE TITLE
Are you looking for contributors?

### ISSUE THREAD

**Issue by rossmounce** [SimonGreenhill/LangPhyDB#1]
Great work, I like it.

Are you looking for bibliographic data contributors? 

Looks like this kind of endeavor could/should be crowdsourced. You'll need some kind of guidelines for contributors in your readme (or somewhere).

I had a quick look and I don't think you've got this study: 

Kassian, Alexei S.. "Linguistic homoplasy and phylogeny reconstruction. The cases of Lezgian and Tsezic languages (North Caucasus) " Folia Linguistica, vol. 51, no. s38-s1, 2017, pp. 217-262. https://doi.org/10.1515/flih-2017-0008

I have previously contributed to somewhat analagous crowdsourcing endeavors in morphology-based phylogenetic analyses which are maintained by Graeme T. Lloyd: https://www.graemetlloyd.com/matr.html  some interesting parallels?

**Comment by SimonGreenhill** [comment]
Hi @rossmounce  -- yes, I guess so. This started mainly for my records (i.e. I wanted to make sure I didn't keep citing papers from my friends all the time), but I'm happy for others to help if they want to. I'll see if I can put together a contrib. guide.

I actually came across your morphology database a number of years ago, and enjoyed it :)

(& thanks for Kassian, I've added that to my TO-DO list).
