### ISSUE TITLE
Scope: studies using language + other non-language data, used in a phylogenetic analysis to be in-scope or not?

### ISSUE THREAD

**Issue by rossmounce** [SimonGreenhill/LangPhyDB#2]
Do you plan to include studies that perform an analysis of language data AND other non-language data in their analyses?

e.g.

Pavel Duda and Jan Zrzavý (2019) Chapter: 12 Towards a global phylogeny of human populations based on genetic and linguistic data. In book: Modern Human Origins and Dispersal. Publisher: Kerns Verlag. Editors: Yonatan Sahle, Hugo Reyes-Centeno, Christian Bentz. ISBN: 978-3-935751-30-8
https://www.researchgate.net/publication/332298707_Towards_a_global_phylogeny_of_human_populations_based_on_genetic_and_linguistic_data

**Comment by SimonGreenhill** [comment]
Yes, but I forgot about that one. Added to the list. I've also fleshed out [README.md](https://github.com/SimonGreenhill/LangPhyDB/blob/main/README.md) to add some more details on scope etc.
