### ISSUE TITLE
2 suggested additions

### ISSUE THREAD

**Issue by erichround** [SimonGreenhill/LangPhyDB#3]
Hi Simon, this is a fantastic resource for the field. Thanks!

Here are two suggested additions to the list:

1. This could count as a TRAIT paper. The family is Pama-Nyungan.

@article{round_evolution_2022,
	title = {Evolution and trade-off dynamics of functional load},
	volume = {24},
	doi = {doi.org/10.3390/e24040507},
	number = {4},
	journal = {Entropy},
	author = {Round, Erich R. and Dockum, Rikker and Ryder, Robin J.},
	year = {2022},
}

2. This could count as REVIEW, TRAIT, and the supp section has a TUTORIAL. The family is Pama-Nyungan.

@article{macklin-cordes_challenges_2022,
	title = {Challenges of sampling and how phylogenetic comparative methods help: {With} a case study of the {Pama}-{Nyungan} laminal contrast},
	volume = {26},
	doi = {doi.org/10.1515/lingty-2021-0025},
	number = {3},
	journal = {Linguistic Typology},
	author = {Macklin-Cordes, Jayden L. and Round, Erich R.},
	year = {2022},
	pages = {533--572},
}

**Comment by SimonGreenhill** [comment]
Thanks Erich. Added to the to-do list.
